### ISSUE TITLE
Parceria Legendas.tv para o Stremio.

### ISSUE THREAD

**Issue by mrcanelas** [darksupremo/legendas.tv-api#2]
Olá, incrível sua API, gostaria de trabalhar junto para levar ela em forma de addon para o Stremio? é uma das grandes solicitações da comunidade.

**Comment by DarkSupremo** [comment]
Fala @mrcanelas, boa noite, no momento estou com tempo bastante apertado, mas se tiver precisando de alguma ajuda pontual, pode chamar..

O maior empecilho que eu vejo seria em relação ao login necessário para fazer o download da legenda no legendas.tv, além do fato do download vir em um zip, e podendo conter múltiplas legendas juntas também..

Tem esse outro projeto também mais antigo que faz essa parte de download (usando a versão antiga desse serviço, v1), extração e escolher a melhor legenda, mas é um app desktop em .net: https://github.com/DarkSupremo/LegendasTvDownloader

**Comment by mrcanelas** [comment]
A questão de login não acredito que seja um problema, a extração pra falar a verdade não sei como fazer mas é possível pois outros addons também fazem a extração de legendas, você tem essa API online em algum lugar pra eu fazer alguns testes?

**Comment by DarkSupremo** [comment]
Tem esse aqui, mas é num host temporário: http://legendasws2.darksupremo.com/
